name: detekt hint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest]
        jdk: [11]
    runs-on: ${{ matrix.os }}
    if: ${{ !contains(github.event.head_commit.message, 'detekt hint skip') }}
    env:
      JDK_VERSION:  ${{ matrix.jdk }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

<<<<<<< HEAD
      - name: Run detekt hint
        uses: Mkohm/kotlin@master
          with:
            args: "--id DangerKotlinAction"
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
=======

      - name: Run detekt hint
        uses: Mkohm/kotlin@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

>>>>>>> 1cf53f602691e3079d71a3d29b8a9760394cf08b
